#!/bin/sh

# <C-x> prefix
while read file
do
        case "$1" in
        "r")
                convert -rotate 90 "$file" "$file" ;;
        "R")
                convert -rotate -90 "$file" "$file" ;;
        "c")
                echo -n "$file" | xsel -b &&
                notify-send "$file copied to clipboard" & ;;
        "C")
                readlink -f "$file" | xsel -b &&
			    notify-send "$(readlink -f "$file") copied to clipboard" & ;;
        esac
done
