#! /bin/sh

$HOME/scripts/autostart.sh
$HOME/.config/polybar/launch.sh
sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium     desktop='^2'
bspc rule -a Kupfer.py           focus=on
bspc rule -a Screenkey           manage=off

bspc rule -a VirtualBox\ Manager desktop='^10'

bspc rule -a Uget-gtk            desktop='^9' state=floating
bspc rule -a Transmission-gtk    desktop='^9' state=floating
bspc rule -a netease-cloud-music desktop='^9' state=floating
bspc rule -a baidunetdisk        desktop='^9' state=floating

bspc rule -a Qq                  desktop='^8' state=floating
bspc rule -a GoldenDict          desktop='^8' state=floating

bspc rule -a Steam               desktop='^7' state=floating
bspc rule -a Wine                             state=floating

