#! /bin/sh

$HOME/scripts/autostart.sh &
$HOME/.config/polybar/launch.sh &
sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config split_ratio          0.52
bspc config border_width         0
bspc config window_gap           20
bspc config focused_border_color '#bd93f9'
#bspc config focus_follows_pointer true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true


bspc rule -a Screenkey           manage=off

bspc rule -a scratchpad          sticky=on state=floating

bspc rule -a VirtualBox\ Manager desktop='^10'

bspc rule -a Uget-gtk            desktop='^9' #state=floating
bspc rule -a Transmission-gtk    desktop='^9' #state=floating

bspc rule -a netease-cloud-music desktop='^8' #state=floating

bspc rule -a Steam               desktop='^7' #state=floating

